// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.CurbStomper;

import org.usfirst.frc4914.CurbStomper.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
	public Joystick primaryJoystick;
	public JoystickButton intakeButton;

    public OI() {
    	primaryJoystick = new Joystick(0);
    	intakeButton = new JoystickButton(primaryJoystick, 1);
    	
    	intakeButton.whileHeld(new RunIntake());

        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
    }
    public Joystick getPrimaryJoystick() {
    	return primaryJoystick;
    }
    public double getPrimaryLJ() { 
    	return primaryJoystick.getRawAxis(1);
    }
    public double getPrimaryRJ() {
    	return primaryJoystick.getRawAxis(5);
    }
}

