// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.CurbStomper;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.TalonSRX;
import edu.wpi.first.wpilibj.Ultrasonic;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SPI.Port;
import edu.wpi.first.wpilibj.TalonSRX;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANSpeedController;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

// 3rd Party Libraries
import com.ctre.CANTalon;
import com.ctre.CANTalon.TalonControlMode;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// Declaration
	public static ADXRS450_Gyro gyro;
	public static CANTalon driveTrainCIMRearLeft;
	public static CANTalon driveTrainCIMFrontLeft;
	public static CANTalon driveTrainCIMRearRight;
	public static CANTalon driveTrainCIMFrontRight;
	public static RobotDrive driveTrainRobotDrive41;
	public static CANTalon climberClimber;
    public static PowerDistributionPanel pDPPowerDistributionPanel1;
    public static Talon c2;
    public static Talon c1;
    public static AnalogInput ultra;

    /*
     *  
     */
    public static void init() {
    	driveTrainCIMRearLeft = new CANTalon(2); // rear left motor
    	driveTrainCIMFrontLeft = new CANTalon(12); // 
    	driveTrainCIMRearRight = new CANTalon(1);
    	driveTrainCIMFrontRight = new CANTalon(11);
    	driveTrainRobotDrive41 = new RobotDrive(driveTrainCIMRearLeft, driveTrainCIMFrontLeft, 
    			driveTrainCIMRearRight, driveTrainCIMFrontRight);
    	climberClimber = new CANTalon(3);
        c1 = new Talon(5);
        pDPPowerDistributionPanel1 = new PowerDistributionPanel(0);
        gyro = new ADXRS450_Gyro(Port.kOnboardCS0);
        c2 = new Talon(6);
        ultra = new AnalogInput(0);
        
        LiveWindow.addSensor("PDP", "PowerDistributionPanel 1", pDPPowerDistributionPanel1);
        LiveWindow.addSensor("Ultra", "Ultra", ultra);
       //  LiveWindow.addActuator("Intake", "Intake", intakeIntake);
        LiveWindow.addActuator("Climber", "Climber", climberClimber);
        LiveWindow.addActuator("RearLeft (2)", "Drivetrain", driveTrainCIMRearLeft);
        LiveWindow.addActuator("FrontLeft (12)", "Drivetrain", driveTrainCIMFrontLeft);
        LiveWindow.addActuator("RearRight (1)", "Drivetrain", driveTrainCIMRearRight);
        LiveWindow.addActuator("FrontRight (11)", "Drivetrain", driveTrainCIMFrontRight);
        LiveWindow.addActuator("Drive Train", "Gyro", gyro);
        // LiveWindow.addActuator("Shooter", "Shooter", shooter1);
    }
}
