// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.CurbStomper.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * 
 */
public class AUTOMiddleHook extends CommandGroup {

    public AUTOMiddleHook() {
    	/*
    	// requires(Robot.driveTrain);
    	addSequential(new DriveBackward(), 1.5);
    	// addSequential(new TrackTarget());
    	addSequential(new AUTODelay(), 3);
    	addSequential(new DriveForward(), 1.5);
    	addSequential(new TrackTarget());
    	addSequential(new AUTODelay(), 3);
    	addSequential(new DriveForward(), 0.7);
    	*/
    	/*
    	addSequential(new DriveUntil(69));
    	addSequential(new AUTODelay(), 4);
    	addSequential(new DriveForward(), 0.7);
    	addSequential(new DriveUntil(69));
    	*/
    	addSequential(new DriveBackward(), 2.3);
    }
}