// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4914.CurbStomper.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4914.CurbStomper.Robot;
import edu.wpi.first.wpilibj.command.PIDCommand;

/**
 *
 */
public class TrackTarget extends PIDCommand {
	
	public static int setpoint = 100;
	public static final int distanceSetpoint = 57;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public TrackTarget() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	super("TrackTarget", 0.1, 1, 1, 0.005);
        
    	getPIDController().setContinuous(false);
        getPIDController().setAbsoluteTolerance(2);
        getPIDController().setOutputRange(-0.1, 0.1);
    }

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        return Robot.getGoalX();

    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	Robot.driveTrain.cumL = output;
    	Robot.driveTrain.cumR = -output;
    	Robot.driveTrain.tankDrive(0.2, 0.2);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	setTimeout(1);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	System.out.println(Robot.getGoalX());
    	// setpoint = (int) ((Robot.getGoalY()+43)/1.2557);
    	setpoint = (int) ((Math.log(Robot.getGoalX()) - Math.log(47.875))/0.0083);
    	getPIDController().setSetpoint(setpoint);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        // return getPIDController().onTarget();
    	return isTimedOut() && Robot.getGoalY() < distanceSetpoint;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.stop();
    	Robot.driveTrain.cumL = 0;
    	Robot.driveTrain.cumR = 0;
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
